// [[ARABIC_HEADER]] هذا الملف (client-app/src/lib/countries.ts) جزء من مشروع HM CAR ويحتوي تعليقات عربية لضمان الوضوح.

export type CountryDialCode = {
  code: string
  dial: string
  nameEn: string
  nameAr?: string
}

export const countryDialCodes: CountryDialCode[] = [
  { code: "AF", dial: "+93", nameEn: "Afghanistan", nameAr: "أفغانستان" },
  { code: "AL", dial: "+355", nameEn: "Albania", nameAr: "ألبانيا" },
  { code: "DZ", dial: "+213", nameEn: "Algeria", nameAr: "الجزائر" },
  { code: "AS", dial: "+1684", nameEn: "American Samoa", nameAr: "ساموا الأمريكية" },
  { code: "AD", dial: "+376", nameEn: "Andorra", nameAr: "أندورا" },
  { code: "AO", dial: "+244", nameEn: "Angola", nameAr: "أنغولا" },
  { code: "AI", dial: "+1264", nameEn: "Anguilla", nameAr: "أنغويلا" },
  { code: "AG", dial: "+1268", nameEn: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا" },
  { code: "AR", dial: "+54", nameEn: "Argentina", nameAr: "الأرجنتين" },
  { code: "AM", dial: "+374", nameEn: "Armenia", nameAr: "أرمينيا" },
  { code: "AW", dial: "+297", nameEn: "Aruba", nameAr: "أروبا" },
  { code: "AU", dial: "+61", nameEn: "Australia", nameAr: "أستراليا" },
  { code: "AT", dial: "+43", nameEn: "Austria", nameAr: "النمسا" },
  { code: "AZ", dial: "+994", nameEn: "Azerbaijan", nameAr: "أذربيجان" },
  { code: "BS", dial: "+1242", nameEn: "Bahamas", nameAr: "جزر البهاما" },
  { code: "BH", dial: "+973", nameEn: "Bahrain", nameAr: "البحرين" },
  { code: "BD", dial: "+880", nameEn: "Bangladesh", nameAr: "بنغلاديش" },
  { code: "BB", dial: "+1246", nameEn: "Barbados", nameAr: "بربادوس" },
  { code: "BY", dial: "+375", nameEn: "Belarus", nameAr: "بيلاروسيا" },
  { code: "BE", dial: "+32", nameEn: "Belgium", nameAr: "بلجيكا" },
  { code: "BZ", dial: "+501", nameEn: "Belize", nameAr: "بيليز" },
  { code: "BJ", dial: "+229", nameEn: "Benin", nameAr: "بنن" },
  { code: "BM", dial: "+1441", nameEn: "Bermuda", nameAr: "برمودا" },
  { code: "BT", dial: "+975", nameEn: "Bhutan", nameAr: "بوتان" },
  { code: "BO", dial: "+591", nameEn: "Bolivia", nameAr: "بوليفيا" },
  { code: "BA", dial: "+387", nameEn: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك" },
  { code: "BW", dial: "+267", nameEn: "Botswana", nameAr: "بوتسوانا" },
  { code: "BR", dial: "+55", nameEn: "Brazil", nameAr: "البرازيل" },
  { code: "VG", dial: "+1284", nameEn: "British Virgin Islands", nameAr: "جزر فيرجن البريطانية" },
  { code: "BN", dial: "+673", nameEn: "Brunei", nameAr: "بروناي" },
  { code: "BG", dial: "+359", nameEn: "Bulgaria", nameAr: "بلغاريا" },
  { code: "BF", dial: "+226", nameEn: "Burkina Faso", nameAr: "بوركينا فاسو" },
  { code: "BI", dial: "+257", nameEn: "Burundi", nameAr: "بوروندي" },
  { code: "KH", dial: "+855", nameEn: "Cambodia", nameAr: "كمبوديا" },
  { code: "CM", dial: "+237", nameEn: "Cameroon", nameAr: "الكاميرون" },
  { code: "CA", dial: "+1", nameEn: "Canada", nameAr: "كندا" },
  { code: "CV", dial: "+238", nameEn: "Cape Verde", nameAr: "الرأس الأخضر" },
  { code: "BQ", dial: "+599", nameEn: "Caribbean Netherlands", nameAr: "هولندا الكاريبية" },
  { code: "KY", dial: "+1345", nameEn: "Cayman Islands", nameAr: "جزر كايمان" },
  { code: "CF", dial: "+236", nameEn: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى" },
  { code: "TD", dial: "+235", nameEn: "Chad", nameAr: "تشاد" },
  { code: "CL", dial: "+56", nameEn: "Chile", nameAr: "تشيلي" },
  { code: "CN", dial: "+86", nameEn: "China", nameAr: "الصين" },
  { code: "CX", dial: "+61", nameEn: "Christmas Island", nameAr: "جزيرة كريسماس" },
  { code: "CC", dial: "+61", nameEn: "Cocos (Keeling) Islands", nameAr: "جزر كوكوس" },
  { code: "CO", dial: "+57", nameEn: "Colombia", nameAr: "كولومبيا" },
  { code: "KM", dial: "+269", nameEn: "Comoros", nameAr: "جزر القمر" },
  { code: "CG", dial: "+242", nameEn: "Congo", nameAr: "الكونغو" },
  { code: "CD", dial: "+243", nameEn: "Congo (DRC)", nameAr: "الكونغو الديمقراطية" },
  { code: "CK", dial: "+682", nameEn: "Cook Islands", nameAr: "جزر كوك" },
  { code: "CR", dial: "+506", nameEn: "Costa Rica", nameAr: "كوستاريكا" },
  { code: "CI", dial: "+225", nameEn: "Côte d’Ivoire", nameAr: "ساحل العاج" },
  { code: "HR", dial: "+385", nameEn: "Croatia", nameAr: "كرواتيا" },
  { code: "CU", dial: "+53", nameEn: "Cuba", nameAr: "كوبا" },
  { code: "CW", dial: "+599", nameEn: "Curaçao", nameAr: "كوراساو" },
  { code: "CY", dial: "+357", nameEn: "Cyprus", nameAr: "قبرص" },
  { code: "CZ", dial: "+420", nameEn: "Czechia", nameAr: "التشيك" },
  { code: "DK", dial: "+45", nameEn: "Denmark", nameAr: "الدنمارك" },
  { code: "DJ", dial: "+253", nameEn: "Djibouti", nameAr: "جيبوتي" },
  { code: "DM", dial: "+1767", nameEn: "Dominica", nameAr: "دومينيكا" },
  { code: "DO", dial: "+1", nameEn: "Dominican Republic", nameAr: "جمهورية الدومينيكان" },
  { code: "EC", dial: "+593", nameEn: "Ecuador", nameAr: "الإكوادور" },
  { code: "EG", dial: "+20", nameEn: "Egypt", nameAr: "مصر" },
  { code: "SV", dial: "+503", nameEn: "El Salvador", nameAr: "السلفادور" },
  { code: "GQ", dial: "+240", nameEn: "Equatorial Guinea", nameAr: "غينيا الاستوائية" },
  { code: "ER", dial: "+291", nameEn: "Eritrea", nameAr: "إريتريا" },
  { code: "EE", dial: "+372", nameEn: "Estonia", nameAr: "إستونيا" },
  { code: "SZ", dial: "+268", nameEn: "Eswatini", nameAr: "إسواتيني" },
  { code: "ET", dial: "+251", nameEn: "Ethiopia", nameAr: "إثيوبيا" },
  { code: "FK", dial: "+500", nameEn: "Falkland Islands", nameAr: "جزر فوكلاند" },
  { code: "FO", dial: "+298", nameEn: "Faroe Islands", nameAr: "جزر فارو" },
  { code: "FJ", dial: "+679", nameEn: "Fiji", nameAr: "فيجي" },
  { code: "FI", dial: "+358", nameEn: "Finland", nameAr: "فنلندا" },
  { code: "FR", dial: "+33", nameEn: "France", nameAr: "فرنسا" },
  { code: "GF", dial: "+594", nameEn: "French Guiana", nameAr: "غويانا الفرنسية" },
  { code: "PF", dial: "+689", nameEn: "French Polynesia", nameAr: "بولينيزيا الفرنسية" },
  { code: "GA", dial: "+241", nameEn: "Gabon", nameAr: "الغابون" },
  { code: "GM", dial: "+220", nameEn: "Gambia", nameAr: "غامبيا" },
  { code: "GE", dial: "+995", nameEn: "Georgia", nameAr: "جورجيا" },
  { code: "DE", dial: "+49", nameEn: "Germany", nameAr: "ألمانيا" },
  { code: "GH", dial: "+233", nameEn: "Ghana", nameAr: "غانا" },
  { code: "GI", dial: "+350", nameEn: "Gibraltar", nameAr: "جبل طارق" },
  { code: "GR", dial: "+30", nameEn: "Greece", nameAr: "اليونان" },
  { code: "GL", dial: "+299", nameEn: "Greenland", nameAr: "جرينلاند" },
  { code: "GD", dial: "+1473", nameEn: "Grenada", nameAr: "غرينادا" },
  { code: "GP", dial: "+590", nameEn: "Guadeloupe", nameAr: "جوادلوب" },
  { code: "GU", dial: "+1671", nameEn: "Guam", nameAr: "غوام" },
  { code: "GT", dial: "+502", nameEn: "Guatemala", nameAr: "غواتيمالا" },
  { code: "GG", dial: "+44", nameEn: "Guernsey", nameAr: "غيرنزي" },
  { code: "GN", dial: "+224", nameEn: "Guinea", nameAr: "غينيا" },
  { code: "GW", dial: "+245", nameEn: "Guinea-Bissau", nameAr: "غينيا بيساو" },
  { code: "GY", dial: "+592", nameEn: "Guyana", nameAr: "غيانا" },
  { code: "HT", dial: "+509", nameEn: "Haiti", nameAr: "هايتي" },
  { code: "HN", dial: "+504", nameEn: "Honduras", nameAr: "هندوراس" },
  { code: "HK", dial: "+852", nameEn: "Hong Kong", nameAr: "هونغ كونغ" },
  { code: "HU", dial: "+36", nameEn: "Hungary", nameAr: "المجر" },
  { code: "IS", dial: "+354", nameEn: "Iceland", nameAr: "آيسلندا" },
  { code: "IN", dial: "+91", nameEn: "India", nameAr: "الهند" },
  { code: "ID", dial: "+62", nameEn: "Indonesia", nameAr: "إندونيسيا" },
  { code: "IR", dial: "+98", nameEn: "Iran", nameAr: "إيران" },
  { code: "IQ", dial: "+964", nameEn: "Iraq", nameAr: "العراق" },
  { code: "IE", dial: "+353", nameEn: "Ireland", nameAr: "إيرلندا" },
  { code: "IM", dial: "+44", nameEn: "Isle of Man", nameAr: "جزيرة مان" },
  { code: "IL", dial: "+972", nameEn: "Israel", nameAr: "إسرائيل" },
  { code: "IT", dial: "+39", nameEn: "Italy", nameAr: "إيطاليا" },
  { code: "JM", dial: "+1", nameEn: "Jamaica", nameAr: "جامايكا" },
  { code: "JP", dial: "+81", nameEn: "Japan", nameAr: "اليابان" },
  { code: "JE", dial: "+44", nameEn: "Jersey", nameAr: "جيرزي" },
  { code: "JO", dial: "+962", nameEn: "Jordan", nameAr: "الأردن" },
  { code: "KZ", dial: "+7", nameEn: "Kazakhstan", nameAr: "كازاخستان" },
  { code: "KE", dial: "+254", nameEn: "Kenya", nameAr: "كينيا" },
  { code: "KI", dial: "+686", nameEn: "Kiribati", nameAr: "كيريباتي" },
  { code: "KW", dial: "+965", nameEn: "Kuwait", nameAr: "الكويت" },
  { code: "KG", dial: "+996", nameEn: "Kyrgyzstan", nameAr: "قرغيزستان" },
  { code: "LA", dial: "+856", nameEn: "Laos", nameAr: "لاوس" },
  { code: "LV", dial: "+371", nameEn: "Latvia", nameAr: "لاتفيا" },
  { code: "LB", dial: "+961", nameEn: "Lebanon", nameAr: "لبنان" },
  { code: "LS", dial: "+266", nameEn: "Lesotho", nameAr: "ليسوتو" },
  { code: "LR", dial: "+231", nameEn: "Liberia", nameAr: "ليبيريا" },
  { code: "LY", dial: "+218", nameEn: "Libya", nameAr: "ليبيا" },
  { code: "LI", dial: "+423", nameEn: "Liechtenstein", nameAr: "ليختنشتاين" },
  { code: "LT", dial: "+370", nameEn: "Lithuania", nameAr: "ليتوانيا" },
  { code: "LU", dial: "+352", nameEn: "Luxembourg", nameAr: "لوكسمبورغ" },
  { code: "MO", dial: "+853", nameEn: "Macao", nameAr: "ماكاو" },
  { code: "MG", dial: "+261", nameEn: "Madagascar", nameAr: "مدغشقر" },
  { code: "MW", dial: "+265", nameEn: "Malawi", nameAr: "مالاوي" },
  { code: "MY", dial: "+60", nameEn: "Malaysia", nameAr: "ماليزيا" },
  { code: "MV", dial: "+960", nameEn: "Maldives", nameAr: "المالديف" },
  { code: "ML", dial: "+223", nameEn: "Mali", nameAr: "مالي" },
  { code: "MT", dial: "+356", nameEn: "Malta", nameAr: "مالطا" },
  { code: "MH", dial: "+692", nameEn: "Marshall Islands", nameAr: "جزر مارشال" },
  { code: "MQ", dial: "+596", nameEn: "Martinique", nameAr: "مارتينيك" },
  { code: "MR", dial: "+222", nameEn: "Mauritania", nameAr: "موريتانيا" },
  { code: "MU", dial: "+230", nameEn: "Mauritius", nameAr: "موريشيوس" },
  { code: "YT", dial: "+262", nameEn: "Mayotte", nameAr: "مايوت" },
  { code: "MX", dial: "+52", nameEn: "Mexico", nameAr: "المكسيك" },
  { code: "FM", dial: "+691", nameEn: "Micronesia", nameAr: "ميكرونيزيا" },
  { code: "MD", dial: "+373", nameEn: "Moldova", nameAr: "مولدوفا" },
  { code: "MC", dial: "+377", nameEn: "Monaco", nameAr: "موناكو" },
  { code: "MN", dial: "+976", nameEn: "Mongolia", nameAr: "منغوليا" },
  { code: "ME", dial: "+382", nameEn: "Montenegro", nameAr: "الجبل الأسود" },
  { code: "MS", dial: "+1664", nameEn: "Montserrat", nameAr: "مونتسرات" },
  { code: "MA", dial: "+212", nameEn: "Morocco", nameAr: "المغرب" },
  { code: "MZ", dial: "+258", nameEn: "Mozambique", nameAr: "موزمبيق" },
  { code: "MM", dial: "+95", nameEn: "Myanmar", nameAr: "ميانمار" },
  { code: "NA", dial: "+264", nameEn: "Namibia", nameAr: "ناميبيا" },
  { code: "NR", dial: "+674", nameEn: "Nauru", nameAr: "ناورو" },
  { code: "NP", dial: "+977", nameEn: "Nepal", nameAr: "نيبال" },
  { code: "NL", dial: "+31", nameEn: "Netherlands", nameAr: "هولندا" },
  { code: "NC", dial: "+687", nameEn: "New Caledonia", nameAr: "كاليدونيا الجديدة" },
  { code: "NZ", dial: "+64", nameEn: "New Zealand", nameAr: "نيوزيلندا" },
  { code: "NI", dial: "+505", nameEn: "Nicaragua", nameAr: "نيكاراغوا" },
  { code: "NE", dial: "+227", nameEn: "Niger", nameAr: "النيجر" },
  { code: "NG", dial: "+234", nameEn: "Nigeria", nameAr: "نيجيريا" },
  { code: "NU", dial: "+683", nameEn: "Niue", nameAr: "نييوي" },
  { code: "NF", dial: "+672", nameEn: "Norfolk Island", nameAr: "جزيرة نورفولك" },
  { code: "KP", dial: "+850", nameEn: "North Korea", nameAr: "كوريا الشمالية" },
  { code: "MK", dial: "+389", nameEn: "North Macedonia", nameAr: "مقدونيا الشمالية" },
  { code: "MP", dial: "+1670", nameEn: "Northern Mariana Islands", nameAr: "جزر ماريانا الشمالية" },
  { code: "NO", dial: "+47", nameEn: "Norway", nameAr: "النرويج" },
  { code: "OM", dial: "+968", nameEn: "Oman", nameAr: "عُمان" },
  { code: "PK", dial: "+92", nameEn: "Pakistan", nameAr: "باكستان" },
  { code: "PW", dial: "+680", nameEn: "Palau", nameAr: "بالاو" },
  { code: "PS", dial: "+970", nameEn: "Palestine", nameAr: "فلسطين" },
  { code: "PA", dial: "+507", nameEn: "Panama", nameAr: "بنما" },
  { code: "PG", dial: "+675", nameEn: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة" },
  { code: "PY", dial: "+595", nameEn: "Paraguay", nameAr: "باراغواي" },
  { code: "PE", dial: "+51", nameEn: "Peru", nameAr: "بيرو" },
  { code: "PH", dial: "+63", nameEn: "Philippines", nameAr: "الفلبين" },
  { code: "PL", dial: "+48", nameEn: "Poland", nameAr: "بولندا" },
  { code: "PT", dial: "+351", nameEn: "Portugal", nameAr: "البرتغال" },
  { code: "PR", dial: "+1", nameEn: "Puerto Rico", nameAr: "بورتوريكو" },
  { code: "QA", dial: "+974", nameEn: "Qatar", nameAr: "قطر" },
  { code: "RE", dial: "+262", nameEn: "Réunion", nameAr: "ريونيون" },
  { code: "RO", dial: "+40", nameEn: "Romania", nameAr: "رومانيا" },
  { code: "RU", dial: "+7", nameEn: "Russia", nameAr: "روسيا" },
  { code: "RW", dial: "+250", nameEn: "Rwanda", nameAr: "رواندا" },
  { code: "BL", dial: "+590", nameEn: "Saint Barthélemy", nameAr: "سانت بارثيليمي" },
  { code: "SH", dial: "+290", nameEn: "Saint Helena", nameAr: "سانت هيلينا" },
  { code: "KN", dial: "+1869", nameEn: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس" },
  { code: "LC", dial: "+1758", nameEn: "Saint Lucia", nameAr: "سانت لوسيا" },
  { code: "MF", dial: "+590", nameEn: "Saint Martin", nameAr: "سانت مارتن" },
  { code: "PM", dial: "+508", nameEn: "Saint Pierre and Miquelon", nameAr: "سان بيير وميكلون" },
  { code: "VC", dial: "+1784", nameEn: "Saint Vincent and the Grenadines", nameAr: "سانت فينسنت والغرينادين" },
  { code: "WS", dial: "+685", nameEn: "Samoa", nameAr: "ساموا" },
  { code: "SM", dial: "+378", nameEn: "San Marino", nameAr: "سان مارينو" },
  { code: "ST", dial: "+239", nameEn: "São Tomé and Príncipe", nameAr: "ساو تومي وبرينسيبي" },
  { code: "SA", dial: "+966", nameEn: "Saudi Arabia", nameAr: "السعودية" },
  { code: "SN", dial: "+221", nameEn: "Senegal", nameAr: "السنغال" },
  { code: "RS", dial: "+381", nameEn: "Serbia", nameAr: "صربيا" },
  { code: "SC", dial: "+248", nameEn: "Seychelles", nameAr: "سيشل" },
  { code: "SL", dial: "+232", nameEn: "Sierra Leone", nameAr: "سيراليون" },
  { code: "SG", dial: "+65", nameEn: "Singapore", nameAr: "سنغافورة" },
  { code: "SX", dial: "+1721", nameEn: "Sint Maarten", nameAr: "سينت مارتن" },
  { code: "SK", dial: "+421", nameEn: "Slovakia", nameAr: "سلوفاكيا" },
  { code: "SI", dial: "+386", nameEn: "Slovenia", nameAr: "سلوفينيا" },
  { code: "SB", dial: "+677", nameEn: "Solomon Islands", nameAr: "جزر سليمان" },
  { code: "SO", dial: "+252", nameEn: "Somalia", nameAr: "الصومال" },
  { code: "ZA", dial: "+27", nameEn: "South Africa", nameAr: "جنوب أفريقيا" },
  { code: "KR", dial: "+82", nameEn: "South Korea", nameAr: "كوريا الجنوبية" },
  { code: "SS", dial: "+211", nameEn: "South Sudan", nameAr: "جنوب السودان" },
  { code: "ES", dial: "+34", nameEn: "Spain", nameAr: "إسبانيا" },
  { code: "LK", dial: "+94", nameEn: "Sri Lanka", nameAr: "سريلانكا" },
  { code: "SD", dial: "+249", nameEn: "Sudan", nameAr: "السودان" },
  { code: "SR", dial: "+597", nameEn: "Suriname", nameAr: "سورينام" },
  { code: "SE", dial: "+46", nameEn: "Sweden", nameAr: "السويد" },
  { code: "CH", dial: "+41", nameEn: "Switzerland", nameAr: "سويسرا" },
  { code: "SY", dial: "+963", nameEn: "Syria", nameAr: "سوريا" },
  { code: "TW", dial: "+886", nameEn: "Taiwan", nameAr: "تايوان" },
  { code: "TJ", dial: "+992", nameEn: "Tajikistan", nameAr: "طاجيكستان" },
  { code: "TZ", dial: "+255", nameEn: "Tanzania", nameAr: "تنزانيا" },
  { code: "TH", dial: "+66", nameEn: "Thailand", nameAr: "تايلاند" },
  { code: "TL", dial: "+670", nameEn: "Timor-Leste", nameAr: "تيمور الشرقية" },
  { code: "TG", dial: "+228", nameEn: "Togo", nameAr: "توجو" },
  { code: "TK", dial: "+690", nameEn: "Tokelau", nameAr: "توكيلو" },
  { code: "TO", dial: "+676", nameEn: "Tonga", nameAr: "تونغا" },
  { code: "TT", dial: "+1868", nameEn: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو" },
  { code: "TN", dial: "+216", nameEn: "Tunisia", nameAr: "تونس" },
  { code: "TR", dial: "+90", nameEn: "Turkey", nameAr: "تركيا" },
  { code: "TM", dial: "+993", nameEn: "Turkmenistan", nameAr: "تركمانستان" },
  { code: "TC", dial: "+1649", nameEn: "Turks and Caicos Islands", nameAr: "جزر توركس وكايكوس" },
  { code: "TV", dial: "+688", nameEn: "Tuvalu", nameAr: "توفالو" },
  { code: "UG", dial: "+256", nameEn: "Uganda", nameAr: "أوغندا" },
  { code: "UA", dial: "+380", nameEn: "Ukraine", nameAr: "أوكرانيا" },
  { code: "AE", dial: "+971", nameEn: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة" },
  { code: "GB", dial: "+44", nameEn: "United Kingdom", nameAr: "المملكة المتحدة" },
  { code: "US", dial: "+1", nameEn: "United States", nameAr: "الولايات المتحدة" },
  { code: "UY", dial: "+598", nameEn: "Uruguay", nameAr: "أوروغواي" },
  { code: "UZ", dial: "+998", nameEn: "Uzbekistan", nameAr: "أوزبكستان" },
  { code: "VU", dial: "+678", nameEn: "Vanuatu", nameAr: "فانواتو" },
  { code: "VA", dial: "+379", nameEn: "Vatican City", nameAr: "الفاتيكان" },
  { code: "VE", dial: "+58", nameEn: "Venezuela", nameAr: "فنزويلا" },
  { code: "VN", dial: "+84", nameEn: "Vietnam", nameAr: "فيتنام" },
  { code: "WF", dial: "+681", nameEn: "Wallis and Futuna", nameAr: "واليس وفوتونا" },
  { code: "YE", dial: "+967", nameEn: "Yemen", nameAr: "اليمن" },
  { code: "ZM", dial: "+260", nameEn: "Zambia", nameAr: "زامبيا" },
  { code: "ZW", dial: "+263", nameEn: "Zimbabwe", nameAr: "زيمبابوي" }
]
